//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebApplication.EmployeeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/WCFproject.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientWebApplication.EmployeeService.EmployeeKnownType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientWebApplication.EmployeeService.FullTimeEmployee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientWebApplication.EmployeeService.PartTimeEmployee))]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeKnownType", Namespace="http://schemas.datacontract.org/2004/07/WCFproject.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientWebApplication.EmployeeService.FullTimeEmployee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientWebApplication.EmployeeService.PartTimeEmployee))]
    public partial class EmployeeKnownType : ClientWebApplication.EmployeeService.Employee {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientWebApplication.EmployeeService.EmployeeType EmployeeTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientWebApplication.EmployeeService.EmployeeType EmployeeType {
            get {
                return this.EmployeeTypeField;
            }
            set {
                if ((this.EmployeeTypeField.Equals(value) != true)) {
                    this.EmployeeTypeField = value;
                    this.RaisePropertyChanged("EmployeeType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullTimeEmployee", Namespace="http://schemas.datacontract.org/2004/07/WCFproject.Models")]
    [System.SerializableAttribute()]
    public partial class FullTimeEmployee : ClientWebApplication.EmployeeService.EmployeeKnownType {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnnualSalaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnnualSalary {
            get {
                return this.AnnualSalaryField;
            }
            set {
                if ((this.AnnualSalaryField.Equals(value) != true)) {
                    this.AnnualSalaryField = value;
                    this.RaisePropertyChanged("AnnualSalary");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartTimeEmployee", Namespace="http://schemas.datacontract.org/2004/07/WCFproject.Models")]
    [System.SerializableAttribute()]
    public partial class PartTimeEmployee : ClientWebApplication.EmployeeService.EmployeeKnownType {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HourlyPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HoursWorkedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HourlyPay {
            get {
                return this.HourlyPayField;
            }
            set {
                if ((this.HourlyPayField.Equals(value) != true)) {
                    this.HourlyPayField = value;
                    this.RaisePropertyChanged("HourlyPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HoursWorked {
            get {
                return this.HoursWorkedField;
            }
            set {
                if ((this.HoursWorkedField.Equals(value) != true)) {
                    this.HoursWorkedField = value;
                    this.RaisePropertyChanged("HoursWorked");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeType", Namespace="http://schemas.datacontract.org/2004/07/WCFproject.Models")]
    public enum EmployeeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Null = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullTimeEmployee = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartTimeEmployee = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployee", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeResponse")]
        ClientWebApplication.EmployeeService.Employee GetEmployee(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployee", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeResponse")]
        System.Threading.Tasks.Task<ClientWebApplication.EmployeeService.Employee> GetEmployeeAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/SaveEmployee", ReplyAction="http://tempuri.org/IEmployeeService/SaveEmployeeResponse")]
        void SaveEmployee(ClientWebApplication.EmployeeService.Employee employee, ClientWebApplication.EmployeeService.EmployeeKnownType e1, ClientWebApplication.EmployeeService.PartTimeEmployee e2, ClientWebApplication.EmployeeService.FullTimeEmployee e3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/SaveEmployee", ReplyAction="http://tempuri.org/IEmployeeService/SaveEmployeeResponse")]
        System.Threading.Tasks.Task SaveEmployeeAsync(ClientWebApplication.EmployeeService.Employee employee, ClientWebApplication.EmployeeService.EmployeeKnownType e1, ClientWebApplication.EmployeeService.PartTimeEmployee e2, ClientWebApplication.EmployeeService.FullTimeEmployee e3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeKnownType", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeKnownTypeResponse")]
        ClientWebApplication.EmployeeService.EmployeeInfo GetEmployeeKnownType(ClientWebApplication.EmployeeService.EmployeeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeKnownType", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeKnownTypeResponse")]
        System.Threading.Tasks.Task<ClientWebApplication.EmployeeService.EmployeeInfo> GetEmployeeKnownTypeAsync(ClientWebApplication.EmployeeService.EmployeeRequest request);
        
        // CODEGEN: Generating message contract since the operation SaveEmployeeKnownType is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/SaveEmployeeKnownType", ReplyAction="http://tempuri.org/IEmployeeService/SaveEmployeeKnownTypeResponse")]
        ClientWebApplication.EmployeeService.SaveEmployeeKnownTypeResponse SaveEmployeeKnownType(ClientWebApplication.EmployeeService.EmployeeInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/SaveEmployeeKnownType", ReplyAction="http://tempuri.org/IEmployeeService/SaveEmployeeKnownTypeResponse")]
        System.Threading.Tasks.Task<ClientWebApplication.EmployeeService.SaveEmployeeKnownTypeResponse> SaveEmployeeKnownTypeAsync(ClientWebApplication.EmployeeService.EmployeeInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeRequestObject", WrapperNamespace="http://MyCompany.com/Employee", IsWrapped=true)]
    public partial class EmployeeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://MyCompany.com/Employee")]
        public string LicenseKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyCompany.com/Employee", Order=0)]
        public int EmployeeId;
        
        public EmployeeRequest() {
        }
        
        public EmployeeRequest(string LicenseKey, int EmployeeId) {
            this.LicenseKey = LicenseKey;
            this.EmployeeId = EmployeeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeInfoObject", WrapperNamespace="http://MyCompany.com/Employee", IsWrapped=true)]
    public partial class EmployeeInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyCompany.com/Employee", Order=0)]
        public int Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyCompany.com/Employee", Order=1)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyCompany.com/Employee", Order=2)]
        public string Gender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyCompany.com/Employee", Order=3)]
        public System.DateTime DOB;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyCompany.com/Employee", Order=4)]
        public ClientWebApplication.EmployeeService.EmployeeType EmployeeType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyCompany.com/Employee", Order=5)]
        public int AnnualSalary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyCompany.com/Employee", Order=6)]
        public int HourlyPay;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MyCompany.com/Employee", Order=7)]
        public int HoursWorked;
        
        public EmployeeInfo() {
        }
        
        public EmployeeInfo(int Id, string Name, string Gender, System.DateTime DOB, ClientWebApplication.EmployeeService.EmployeeType EmployeeType, int AnnualSalary, int HourlyPay, int HoursWorked) {
            this.Id = Id;
            this.Name = Name;
            this.Gender = Gender;
            this.DOB = DOB;
            this.EmployeeType = EmployeeType;
            this.AnnualSalary = AnnualSalary;
            this.HourlyPay = HourlyPay;
            this.HoursWorked = HoursWorked;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveEmployeeKnownTypeResponse {
        
        public SaveEmployeeKnownTypeResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : ClientWebApplication.EmployeeService.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<ClientWebApplication.EmployeeService.IEmployeeService>, ClientWebApplication.EmployeeService.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientWebApplication.EmployeeService.Employee GetEmployee(int Id) {
            return base.Channel.GetEmployee(Id);
        }
        
        public System.Threading.Tasks.Task<ClientWebApplication.EmployeeService.Employee> GetEmployeeAsync(int Id) {
            return base.Channel.GetEmployeeAsync(Id);
        }
        
        public void SaveEmployee(ClientWebApplication.EmployeeService.Employee employee, ClientWebApplication.EmployeeService.EmployeeKnownType e1, ClientWebApplication.EmployeeService.PartTimeEmployee e2, ClientWebApplication.EmployeeService.FullTimeEmployee e3) {
            base.Channel.SaveEmployee(employee, e1, e2, e3);
        }
        
        public System.Threading.Tasks.Task SaveEmployeeAsync(ClientWebApplication.EmployeeService.Employee employee, ClientWebApplication.EmployeeService.EmployeeKnownType e1, ClientWebApplication.EmployeeService.PartTimeEmployee e2, ClientWebApplication.EmployeeService.FullTimeEmployee e3) {
            return base.Channel.SaveEmployeeAsync(employee, e1, e2, e3);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApplication.EmployeeService.EmployeeInfo ClientWebApplication.EmployeeService.IEmployeeService.GetEmployeeKnownType(ClientWebApplication.EmployeeService.EmployeeRequest request) {
            return base.Channel.GetEmployeeKnownType(request);
        }
        
        public int GetEmployeeKnownType(string LicenseKey, int EmployeeId, out string Name, out string Gender, out System.DateTime DOB, out ClientWebApplication.EmployeeService.EmployeeType EmployeeType, out int AnnualSalary, out int HourlyPay, out int HoursWorked) {
            ClientWebApplication.EmployeeService.EmployeeRequest inValue = new ClientWebApplication.EmployeeService.EmployeeRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.EmployeeId = EmployeeId;
            ClientWebApplication.EmployeeService.EmployeeInfo retVal = ((ClientWebApplication.EmployeeService.IEmployeeService)(this)).GetEmployeeKnownType(inValue);
            Name = retVal.Name;
            Gender = retVal.Gender;
            DOB = retVal.DOB;
            EmployeeType = retVal.EmployeeType;
            AnnualSalary = retVal.AnnualSalary;
            HourlyPay = retVal.HourlyPay;
            HoursWorked = retVal.HoursWorked;
            return retVal.Id;
        }
        
        public System.Threading.Tasks.Task<ClientWebApplication.EmployeeService.EmployeeInfo> GetEmployeeKnownTypeAsync(ClientWebApplication.EmployeeService.EmployeeRequest request) {
            return base.Channel.GetEmployeeKnownTypeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApplication.EmployeeService.SaveEmployeeKnownTypeResponse ClientWebApplication.EmployeeService.IEmployeeService.SaveEmployeeKnownType(ClientWebApplication.EmployeeService.EmployeeInfo request) {
            return base.Channel.SaveEmployeeKnownType(request);
        }
        
        public void SaveEmployeeKnownType(int Id, string Name, string Gender, System.DateTime DOB, ClientWebApplication.EmployeeService.EmployeeType EmployeeType, int AnnualSalary, int HourlyPay, int HoursWorked) {
            ClientWebApplication.EmployeeService.EmployeeInfo inValue = new ClientWebApplication.EmployeeService.EmployeeInfo();
            inValue.Id = Id;
            inValue.Name = Name;
            inValue.Gender = Gender;
            inValue.DOB = DOB;
            inValue.EmployeeType = EmployeeType;
            inValue.AnnualSalary = AnnualSalary;
            inValue.HourlyPay = HourlyPay;
            inValue.HoursWorked = HoursWorked;
            ClientWebApplication.EmployeeService.SaveEmployeeKnownTypeResponse retVal = ((ClientWebApplication.EmployeeService.IEmployeeService)(this)).SaveEmployeeKnownType(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebApplication.EmployeeService.SaveEmployeeKnownTypeResponse> ClientWebApplication.EmployeeService.IEmployeeService.SaveEmployeeKnownTypeAsync(ClientWebApplication.EmployeeService.EmployeeInfo request) {
            return base.Channel.SaveEmployeeKnownTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebApplication.EmployeeService.SaveEmployeeKnownTypeResponse> SaveEmployeeKnownTypeAsync(int Id, string Name, string Gender, System.DateTime DOB, ClientWebApplication.EmployeeService.EmployeeType EmployeeType, int AnnualSalary, int HourlyPay, int HoursWorked) {
            ClientWebApplication.EmployeeService.EmployeeInfo inValue = new ClientWebApplication.EmployeeService.EmployeeInfo();
            inValue.Id = Id;
            inValue.Name = Name;
            inValue.Gender = Gender;
            inValue.DOB = DOB;
            inValue.EmployeeType = EmployeeType;
            inValue.AnnualSalary = AnnualSalary;
            inValue.HourlyPay = HourlyPay;
            inValue.HoursWorked = HoursWorked;
            return ((ClientWebApplication.EmployeeService.IEmployeeService)(this)).SaveEmployeeKnownTypeAsync(inValue);
        }
    }
}
