//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebApplication.CompanyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.ICompanyPublicService")]
    public interface ICompanyPublicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyPublicService/GetPublicInformation", ReplyAction="http://tempuri.org/ICompanyPublicService/GetPublicInformationResponse")]
        string GetPublicInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyPublicService/GetPublicInformation", ReplyAction="http://tempuri.org/ICompanyPublicService/GetPublicInformationResponse")]
        System.Threading.Tasks.Task<string> GetPublicInformationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyPublicServiceChannel : ClientWebApplication.CompanyService.ICompanyPublicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyPublicServiceClient : System.ServiceModel.ClientBase<ClientWebApplication.CompanyService.ICompanyPublicService>, ClientWebApplication.CompanyService.ICompanyPublicService {
        
        public CompanyPublicServiceClient() {
        }
        
        public CompanyPublicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyPublicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyPublicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyPublicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPublicInformation() {
            return base.Channel.GetPublicInformation();
        }
        
        public System.Threading.Tasks.Task<string> GetPublicInformationAsync() {
            return base.Channel.GetPublicInformationAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.ICompanyConfidentalService")]
    public interface ICompanyConfidentalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyConfidentalService/GetConfidentalInformation", ReplyAction="http://tempuri.org/ICompanyConfidentalService/GetConfidentalInformationResponse")]
        string GetConfidentalInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyConfidentalService/GetConfidentalInformation", ReplyAction="http://tempuri.org/ICompanyConfidentalService/GetConfidentalInformationResponse")]
        System.Threading.Tasks.Task<string> GetConfidentalInformationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyConfidentalServiceChannel : ClientWebApplication.CompanyService.ICompanyConfidentalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyConfidentalServiceClient : System.ServiceModel.ClientBase<ClientWebApplication.CompanyService.ICompanyConfidentalService>, ClientWebApplication.CompanyService.ICompanyConfidentalService {
        
        public CompanyConfidentalServiceClient() {
        }
        
        public CompanyConfidentalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyConfidentalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyConfidentalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyConfidentalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetConfidentalInformation() {
            return base.Channel.GetConfidentalInformation();
        }
        
        public System.Threading.Tasks.Task<string> GetConfidentalInformationAsync() {
            return base.Channel.GetConfidentalInformationAsync();
        }
    }
}
