//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebApplication.StudentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        private int TotalMarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalMarks {
            get {
                return this.TotalMarksField;
            }
            set {
                if ((this.TotalMarksField.Equals(value) != true)) {
                    this.TotalMarksField = value;
                    this.RaisePropertyChanged("TotalMarks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentService.StudentWebServiceSoap")]
    public interface StudentWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetStudentByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentById", ReplyAction="*")]
        ClientWebApplication.StudentService.GetStudentByIdResponse GetStudentById(ClientWebApplication.StudentService.GetStudentByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentById", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWebApplication.StudentService.GetStudentByIdResponse> GetStudentByIdAsync(ClientWebApplication.StudentService.GetStudentByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentById", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.StudentService.GetStudentByIdRequestBody Body;
        
        public GetStudentByIdRequest() {
        }
        
        public GetStudentByIdRequest(ClientWebApplication.StudentService.GetStudentByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetStudentByIdRequestBody() {
        }
        
        public GetStudentByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.StudentService.GetStudentByIdResponseBody Body;
        
        public GetStudentByIdResponse() {
        }
        
        public GetStudentByIdResponse(ClientWebApplication.StudentService.GetStudentByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWebApplication.StudentService.Student GetStudentByIdResult;
        
        public GetStudentByIdResponseBody() {
        }
        
        public GetStudentByIdResponseBody(ClientWebApplication.StudentService.Student GetStudentByIdResult) {
            this.GetStudentByIdResult = GetStudentByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentWebServiceSoapChannel : ClientWebApplication.StudentService.StudentWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentWebServiceSoapClient : System.ServiceModel.ClientBase<ClientWebApplication.StudentService.StudentWebServiceSoap>, ClientWebApplication.StudentService.StudentWebServiceSoap {
        
        public StudentWebServiceSoapClient() {
        }
        
        public StudentWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApplication.StudentService.GetStudentByIdResponse ClientWebApplication.StudentService.StudentWebServiceSoap.GetStudentById(ClientWebApplication.StudentService.GetStudentByIdRequest request) {
            return base.Channel.GetStudentById(request);
        }
        
        public ClientWebApplication.StudentService.Student GetStudentById(int id) {
            ClientWebApplication.StudentService.GetStudentByIdRequest inValue = new ClientWebApplication.StudentService.GetStudentByIdRequest();
            inValue.Body = new ClientWebApplication.StudentService.GetStudentByIdRequestBody();
            inValue.Body.id = id;
            ClientWebApplication.StudentService.GetStudentByIdResponse retVal = ((ClientWebApplication.StudentService.StudentWebServiceSoap)(this)).GetStudentById(inValue);
            return retVal.Body.GetStudentByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebApplication.StudentService.GetStudentByIdResponse> ClientWebApplication.StudentService.StudentWebServiceSoap.GetStudentByIdAsync(ClientWebApplication.StudentService.GetStudentByIdRequest request) {
            return base.Channel.GetStudentByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebApplication.StudentService.GetStudentByIdResponse> GetStudentByIdAsync(int id) {
            ClientWebApplication.StudentService.GetStudentByIdRequest inValue = new ClientWebApplication.StudentService.GetStudentByIdRequest();
            inValue.Body = new ClientWebApplication.StudentService.GetStudentByIdRequestBody();
            inValue.Body.id = id;
            return ((ClientWebApplication.StudentService.StudentWebServiceSoap)(this)).GetStudentByIdAsync(inValue);
        }
    }
}
