//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebApplication.CalculatorServiceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorServiceWCF.ICalculatorServiceWCF")]
    public interface ICalculatorServiceWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorServiceWCF/Divide", ReplyAction="http://tempuri.org/ICalculatorServiceWCF/DivideResponse")]
        int Divide(int numerator, int denominator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorServiceWCF/Divide", ReplyAction="http://tempuri.org/ICalculatorServiceWCF/DivideResponse")]
        System.Threading.Tasks.Task<int> DivideAsync(int numerator, int denominator);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorServiceWCFChannel : ClientWebApplication.CalculatorServiceWCF.ICalculatorServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceWCFClient : System.ServiceModel.ClientBase<ClientWebApplication.CalculatorServiceWCF.ICalculatorServiceWCF>, ClientWebApplication.CalculatorServiceWCF.ICalculatorServiceWCF {
        
        public CalculatorServiceWCFClient() {
        }
        
        public CalculatorServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Divide(int numerator, int denominator) {
            return base.Channel.Divide(numerator, denominator);
        }
        
        public System.Threading.Tasks.Task<int> DivideAsync(int numerator, int denominator) {
            return base.Channel.DivideAsync(numerator, denominator);
        }
    }
}
