//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWindowsForms.SimpleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpleService.ISimpleService", CallbackContract=typeof(ClientWindowsForms.SimpleService.ISimpleServiceCallback))]
    public interface ISimpleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/IncrementNumber", ReplyAction="http://tempuri.org/ISimpleService/IncrementNumberResponse")]
        int IncrementNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/IncrementNumber", ReplyAction="http://tempuri.org/ISimpleService/IncrementNumberResponse")]
        System.Threading.Tasks.Task<int> IncrementNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/DisplaySessionId", ReplyAction="http://tempuri.org/ISimpleService/DisplaySessionIdResponse")]
        void DisplaySessionId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/DisplaySessionId", ReplyAction="http://tempuri.org/ISimpleService/DisplaySessionIdResponse")]
        System.Threading.Tasks.Task DisplaySessionIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetEvenNumbers", ReplyAction="http://tempuri.org/ISimpleService/GetEvenNumbersResponse")]
        int[] GetEvenNumbers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetEvenNumbers", ReplyAction="http://tempuri.org/ISimpleService/GetEvenNumbersResponse")]
        System.Threading.Tasks.Task<int[]> GetEvenNumbersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetOddNumbers", ReplyAction="http://tempuri.org/ISimpleService/GetOddNumbersResponse")]
        int[] GetOddNumbers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetOddNumbers", ReplyAction="http://tempuri.org/ISimpleService/GetOddNumbersResponse")]
        System.Threading.Tasks.Task<int[]> GetOddNumbersAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISimpleService/ProgressReport")]
        void ProgressReport();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISimpleService/ProgressReport")]
        System.Threading.Tasks.Task ProgressReportAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISimpleService/DoWork")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISimpleService/DoWork")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetUserName", ReplyAction="http://tempuri.org/ISimpleService/GetUserNameResponse")]
        string GetUserName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetUserName", ReplyAction="http://tempuri.org/ISimpleService/GetUserNameResponse")]
        System.Threading.Tasks.Task<string> GetUserNameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/ReportProgress", ReplyAction="http://tempuri.org/ISimpleService/ReportProgressResponse")]
        void ReportProgress(int percentageCompleted);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleServiceChannel : ClientWindowsForms.SimpleService.ISimpleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleServiceClient : System.ServiceModel.DuplexClientBase<ClientWindowsForms.SimpleService.ISimpleService>, ClientWindowsForms.SimpleService.ISimpleService {
        
        public SimpleServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SimpleServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SimpleServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int IncrementNumber() {
            return base.Channel.IncrementNumber();
        }
        
        public System.Threading.Tasks.Task<int> IncrementNumberAsync() {
            return base.Channel.IncrementNumberAsync();
        }
        
        public void DisplaySessionId() {
            base.Channel.DisplaySessionId();
        }
        
        public System.Threading.Tasks.Task DisplaySessionIdAsync() {
            return base.Channel.DisplaySessionIdAsync();
        }
        
        public int[] GetEvenNumbers() {
            return base.Channel.GetEvenNumbers();
        }
        
        public System.Threading.Tasks.Task<int[]> GetEvenNumbersAsync() {
            return base.Channel.GetEvenNumbersAsync();
        }
        
        public int[] GetOddNumbers() {
            return base.Channel.GetOddNumbers();
        }
        
        public System.Threading.Tasks.Task<int[]> GetOddNumbersAsync() {
            return base.Channel.GetOddNumbersAsync();
        }
        
        public void ProgressReport() {
            base.Channel.ProgressReport();
        }
        
        public System.Threading.Tasks.Task ProgressReportAsync() {
            return base.Channel.ProgressReportAsync();
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string GetUserName() {
            return base.Channel.GetUserName();
        }
        
        public System.Threading.Tasks.Task<string> GetUserNameAsync() {
            return base.Channel.GetUserNameAsync();
        }
    }
}
