//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWindowsForms.HelloServiceIIS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloServiceIIS.IHelloService")]
    public interface IHelloService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetMessage", ReplyAction="http://tempuri.org/IHelloService/GetMessageResponse")]
        string GetMessage(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetMessage", ReplyAction="http://tempuri.org/IHelloService/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetMessageWithoutAnyProtection", ReplyAction="http://tempuri.org/IHelloService/GetMessageWithoutAnyProtectionResponse")]
        string GetMessageWithoutAnyProtection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetMessageWithoutAnyProtection", ReplyAction="http://tempuri.org/IHelloService/GetMessageWithoutAnyProtectionResponse")]
        System.Threading.Tasks.Task<string> GetMessageWithoutAnyProtectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetSignedMessage", ReplyAction="http://tempuri.org/IHelloService/GetSignedMessageResponse")]
        string GetSignedMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetSignedMessage", ReplyAction="http://tempuri.org/IHelloService/GetSignedMessageResponse")]
        System.Threading.Tasks.Task<string> GetSignedMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetSignedAndEncryptedMessage", ReplyAction="http://tempuri.org/IHelloService/GetSignedAndEncryptedMessageResponse")]
        string GetSignedAndEncryptedMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetSignedAndEncryptedMessage", ReplyAction="http://tempuri.org/IHelloService/GetSignedAndEncryptedMessageResponse")]
        System.Threading.Tasks.Task<string> GetSignedAndEncryptedMessageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloServiceChannel : ClientWindowsForms.HelloServiceIIS.IHelloService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceClient : System.ServiceModel.ClientBase<ClientWindowsForms.HelloServiceIIS.IHelloService>, ClientWindowsForms.HelloServiceIIS.IHelloService {
        
        public HelloServiceClient() {
        }
        
        public HelloServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessage(string Name) {
            return base.Channel.GetMessage(Name);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string Name) {
            return base.Channel.GetMessageAsync(Name);
        }
        
        public string GetMessageWithoutAnyProtection() {
            return base.Channel.GetMessageWithoutAnyProtection();
        }
        
        public System.Threading.Tasks.Task<string> GetMessageWithoutAnyProtectionAsync() {
            return base.Channel.GetMessageWithoutAnyProtectionAsync();
        }
        
        public string GetSignedMessage() {
            return base.Channel.GetSignedMessage();
        }
        
        public System.Threading.Tasks.Task<string> GetSignedMessageAsync() {
            return base.Channel.GetSignedMessageAsync();
        }
        
        public string GetSignedAndEncryptedMessage() {
            return base.Channel.GetSignedAndEncryptedMessage();
        }
        
        public System.Threading.Tasks.Task<string> GetSignedAndEncryptedMessageAsync() {
            return base.Channel.GetSignedAndEncryptedMessageAsync();
        }
    }
}
